### ISSUE TITLE
Haml filter support

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#10]
After getting it to work in rails, i notice that the template thing is really only good for ujs in rails. 
I do use ujs, but little, and as i said the goal is Vue.
And since i do templates in haml that means a haml filter.

This was suprisingly quite easy to write, only 5 lines, the compile wrapped in the right kind of module. 
I've made it conditional to whether haml is loaded, just making the issue so the pull can fix it.
Not sure if you want that in your repository, but there it is

**Comment by rubys** [comment]
HAML is an excellent feature; my only comment is that I would prefer that this be in a separate file, for example lib/ruby2js/haml.rb or perhaps lib/ruby2js/filter/haml.rb.  Those that want to opt in would do so by including a require for 'ruby2js/haml' or perhaps 'ruby2js/filter/haml'.  The haml.rb file itself could freely do a require for haml itself.

**Comment by rubys** [comment]
> the template thing is really only good for ujs in rails

Ideally, ruby2js should be usable any place that CoffeScript can be used.  Embedding scripts in HAML is find for short scripts, but eventually you will likely want to factor things out to separate scripts that are pulled in with the asset pipeline.  Let me know what you need, and I can help (I'm comfortable with Rails as a co-author of a book on the subject: https://pragprog.com/book/rails51/agile-web-development-with-rails-5-1).

If you wander into creating Vue components, you will note that the current Vue filter supports a syntax inspired by wunderbar (which in turn was inspired by builder and markaby).  Wunderbar supports being used as a Rails template language.

Finally, I added a HAML test.  Adding a Rails test is a bit of a PITA (see wunderbar for an example), but can be done; and I can sketch it out if you describe how you intend to use ruby2js beyond HAML.

**Comment by dancinglightning** [comment]
Ok, now i remember, yes! I was just so taken with the "born" ruby programmer name (:wink:). My first book, was it even 2.3. Definitely 3 (all those changes!) and 4, now 5 for my students. Great book, well done!

Yes, definitely will want to do sprockets support. I've seen you got tilt in there, so it should be manageable. But i'll play a bit first, maybe next week. 

As to the vue filter, i can't really tell by the code what it does, how it would be useful.
I am not a fan of the inline templates and will create a helper to pull in the handlebar file from some directory (so no wunderbar if i understand that right, even it's such a nice name). 

I'll come back to this after playtime
