### ISSUE TITLE
simple for loop

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#12]
Hi,
i'm trying this out. Some features are handy, but on general i am having problems with the docs:
i'm doing vue and dare i ask what the 1000 lines do?

But now i want to start simple and convert a for loop.
The docs say upto(num) will convert into a for, but for if i just `require "functions"` the convert chokes on it's own :irange output (ie unknown ast type)
If i then require "rubyjs" as well the upto transforms into a Range construct. Quite apart from that changing the meaning of this inside the loop, it refers to a global `R` , which is not defined.

```
  class ProductMethods
    def attribute_for(id , attribute)
      0.upto(self.products.length) do
        product = self.products[i]
```
```
ProductMethods.prototype = {
        attribute_for: function(id, attribute) {
          var self = this;
          (new R.Range(0, this.products.length)).step(1, function() {
            var product = self.products[i];
            var num;

```      
```
 vue.self-7dcd95ec010de570533c67c3762135204387d06046f075e58b4fabfd2e268ab8.js?body=1:573 
    ReferenceError: R is not defined
    at Vue$3.attribute_for (products:827)

```

**Comment by rubys** [comment]
For ruby2js to convert a call to `upto` to a for loop, it needs a loop variable.

Try the following program:

```ruby
input = %{
class ProductMethods
  def attribute_for(id, attributes)
    0.upto(self.products.length) do |i|
     product = self.products[i]
    end
  end
end
}

         
require 'ruby2js/filter/functions'

puts Ruby2JS.convert(input)  
```

As an alternative, you can get the same result using a Ruby `for` loop with a range:

```ruby
input = %{
class ProductMethods
  def attribute_for(id, attributes)
    for i in 0..self.products.length
     product = self.products[i]
    end 
  end     
end      
}         
         
require 'ruby2js/filter/functions'

puts Ruby2JS.convert(input)  
```

The output should be the same in both cases:

```javascript
function ProductMethods() {};

ProductMethods.prototype.attribute_for = function(id, attributes) {
  for (var i = 0; i <= this.products.length; i++) {
    var product = this.products[i]
  }
}
```

P.S.  the Vue filter is indeed undocumented at the moment; but lets treat that as a separate issue?

**Comment by dancinglightning** [comment]
ok, thanks. Works now.
That is strange though, the way it fails when the `|i|` is missing. Maybe a little more doc ?

Still, the question is, will you open the separate issue for vue or shall i?

**Comment by rubys** [comment]
Patches welcome on the documentation. :-)

At the moment, ranges are not supported (see link to notimplemented_spec) as there is no JavaScript equivalent.  However if you include (ruby2j)[http://rubyjs.org/], that library has support for ranges (via a class they provide named `R.Range`), and while the `functions` filter doesn't fully support range, it does have a few cases where there is a reasonable mapping.

As to Vue: how do you expect to use Vue?  In a nutshell, what the `vue` filter provides is an alternative to JSX for use within rendering functions.  They syntax is an implementation of [wunderbar](https://github.com/rubys/wunderbar/blob/master/README.md).  If this is of interest to you, then please do open a separate issue, and ideally provide an example of what you would like to do.

**Comment by dancinglightning** [comment]
I have code like this https://github.com/dancinglightning/ruby_clerks/blob/master/app/views/manage/reports.html.haml
which i am somehow hoping to clean up more ruby-ish

One thing i noticed was the Class -> prototype hash, which could get the code into classes.
But really i was fishing. I am not a fan of html generation in code or html dsl's, so if that is the main focus there, i'm good.

**Comment by rubys** [comment]
That's indeed helpful.

There are basically three ways to use Vue.  One is with string templates.  One is to use HTML as templates.  And one is to use render methods in components.  My tastes run towards the third method (as I come from a React.JS background), but all three approaches have strengths.

Your preference is for the second method, with HAML to generate HTML, and that is fine.

What the Vue filter's current focus is on is creating Vue components.  The render function is a big part of that, but not the whole story.  To demonstrate a taste of what that filter can do, try the following:

```ruby
input = %{
class Component < Vue
  def initialize
    @options = {fullwidth: true, height: 500}
    @kind = "Order"
  end

  def filteredCategories
    [].select {|item| item[index] == @kind}
  end

  def total_for(attributes)
    items = filteredCategories
    all = {}
    for i in 0..items.length
      all[items[i]] = 1
    end
    return all.keys().length
  end
end
}

require 'ruby2js/filter/functions'
require 'ruby2js/filter/vue'

puts Ruby2JS.convert(input)
```

The output should look like this:

```javascript
var Component = Vue.component("component-", {
  data: function() {
    return {options: {fullwidth: true, height: 500}, kind: "Order"}
  },

  methods: {total_for: function(attributes) {
    var items = this.filteredCategories;
    var all = {};

    for (var i = 0; i <= items.length; i++) {
      all[items[i]] = 1
    };

    return Object.keys(all).length
  }},

  computed: {filteredCategories: function() {
    var self = this;

    return [].filter(function(item) {
      return item[index] == self.$data.kind
    })
  }}
})
```

Note how `initialize` was mapped to data.  And the definition of a method with no arguments (and importantly: no parenthesis) is mapped to a computed method.  And the definition of another method was mapped to an ordinary vue method.

Also, note how Ruby's `.select` method was mapped to JavaScript's `.filter` function.  And that `all.keys` was mapped to `Object.keys(all)`.

If this is of interest to you, the next question is whether you can move to Vue components, or (and more likely) if ruby2js's `vue` filter can scan for calls to `Vue.new` and take advantage of the relevant portions of Vue component support in the generation.

**Comment by rubys** [comment]
Upon further reflection: if there is no `render` method or `template`, then instead of generating `Vue.component("name", `, output `View.new(` instead.

**Comment by dancinglightning** [comment]
Well, this is GREAT, just the kind of ting i was hoping.

And maybe i can learn/get into components. Even with rendering (i copied a chart component https://github.com/dancinglightning/ruby_clerks/blob/master/app/views/manage/_chart.html.haml)
With really small components i see the benefit of rendering too, just haven't done that.

'course if you can do that autodetection -> new tingie that's also great. (ps love the methods/computed detection)

**Comment by rubys** [comment]
I've implemented the [autodetection -> new thingie](https://github.com/rubys/ruby2js/commit/08d8f0ce3dd57de2816a0afe455737addd5d2432).

While not a substitute for documentation, I encourage you to scan the [specs](https://github.com/rubys/ruby2js/blob/master/spec/vue_spec.rb) for the Vue filter to get a feeling for what can be done.

Test cases consists of inputs which describe what feels like the natural way to express a concept in Ruby (for example, `initialize` methods) and what would be an idiomatic expression of that concept in JavaScript.  As filters are totally opt-in, the mapping can be framework specific.

Try things out.  The more concrete you can make your suggestions, the better.

**Comment by dancinglightning** [comment]
Ok, i'm trying. That which works works great.
But some questions remain:
- as per ruby habit, i left out `()` as in `all.keys.length` instead of `all.keys().length` and was surprised. As there is no difference in ruby, i thought the parser makes a send out of both and you couldn't distinguish anyway
- i don't like for loops, so i find myself using the `0.upto(items.length)` version, and thinking about that i noticed that in ruby i would probably use `items.length.times {|i| code}` . Does that exist?
- got the part where instance variables become data members, and that's a nice mapping. But my code uses this.start, where @start would map to this.$data.start. Is that the same?
- I know this is not ruby2js related, but what is the difference of the data hash key and the data function? In https://github.com/dancinglightning/ruby_clerks/blob/ruby2js/app/views/manage/reports.html.haml there are both(line 230 and 341), but ruby2js maps the initializer to `data: function()` so when i add a `def data` i get two of those `data: function` and i should think the second overwrites. Question being how to avoid the overwrite or the whole two data thing.

btw, i am happy to document any of these things i learn

**Comment by rubys** [comment]
>   as per ruby habit, i left out () as in all.keys.length instead of all.keys().length and was surprised. As there is no difference in ruby, i thought the parser makes a send out of both and you couldn't distinguish anyway

Obviously, it is possible to distinguish these cases.  Parser::AST::Node.is_method? does this.  The source to that method is in lib/ruby2js/converter.rb.

It is important to realize that filters run at "compile" time, not run time.  So if a simple object had a property named keys, attempts to access that property would be compiled into a method call instead.

>    i don't like for loops, so i find myself using the 0.upto(items.length) version, and thinking about that i noticed that in ruby i would probably use items.length.times {|i| code} . Does that exist?

That would not be difficult to add.  If it were added to the functions filter, it probably should be removed from the underscore filter.

>  got the part where instance variables become data members, and that's a nice mapping. But my code uses this.start, where @start would map to this.$data.start. Is that the same?

Short answer: yes.  Longer answer: in Vue, everything including methods are added to `this`.  `this.$data` would only access data.

>   I know this is not ruby2js related, but what is the difference of the data hash key and the data function? In https://github.com/dancinglightning/ruby_clerks/blob/ruby2js/app/views/manage/reports.html.haml there are both(line 230 and 341), but ruby2js maps the initializer to data: function() so when i add a def data i get two of those data: function and i should think the second overwrites. Question being how to avoid the overwrite or the whole two data thing.

In Vue instances, data can either be a hash, or a function that returns a hash.  In Vue components, data can only be a function.  This could be left as is, or the recently added code that creates Vue instances can attempt to optimize this case.

> btw, i am happy to document any of these things i learn

Excellent!
