### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#13]
Obviously i propose to help you here, otherwise i wouldn't have opened this. Just to sum up the view as a newcomer:
- too little on the overall approach
- little overview
- terse filter docs
- too much philosophy in the beginning of readme

I really think the approach has it's place for the rubyist.
So i propose:
- use wiki for full docs and readme for appetizer
- move the filter list , one per page to wiki, to be expanded later
- have main wiki page that mainly lists the filters
- move the philosophy into wiki page (linked from main and readme)
- change readme to architecture overview, with code examples per filter and links to the wiki.

I could start by moving the filter into the wiki and create the index page.
I fact we could get the wiki as proposed and have a temporary readme there, until you're happy and that can be moved to the README

PS: I have been reading the specs to get an understanding. Even the code. I've written a couple ast based compilers and filters, but .... The specs can be a good start for code examples.

**Comment by dancinglightning** [comment]
no comment ?

**Comment by rubys** [comment]
I invited you as a collaborator.  :-)  I look forward to what you create.

I will admit to not being sure about splitting the filter list to one per page.  Often times, I find myself wanting to do something, so I search that page to see what I can do to produce that result.  In the process, I may find out that I need to include a filter and possibly even a javascript library to produce that result.  This would become harder if this information was split across multiple pages.

**Comment by dancinglightning** [comment]
Yes, thanks for the access. I tend towards the cautious side until i figure how you like it (mostly to avoid disappointment). So i will write issues for everything first.

We can leave the list in the wiki home, if that's an ok place.
Did you read the vue page i started: it's that kind of more elaborate examples that i feel are missing / would help get beginners in.

**Comment by dancinglightning** [comment]
Ok, i've updated the readme with some basics and done the vue page.

Having done that i think this suggestion is no good. Docs need to be next to the code, they just never get  updated otherwise.

I've done a few jekyll pages, but even without that, i think one would need to get some script going to extract the info from the code. Bit like rdoc, but simpler and for this parser case.
This would need some architecture rework, so one can have one case per file (bit like the converter architecture).
If you want we can open another issue for that.
