### ISSUE TITLE
collect

### ISSUE THREAD

**Issue by rubydesign** [rubys/ruby2js#14]
I have a method like this:
```
  def labels
      all = []
      buckets = this.buckets
      for key in buckets
        all.push(buckets[key])
      end
      return all
    end
```
in other words a classic collect in ruby
```
  def labels
     all = this.buckets.collect{|key| this.buckets[key]}
     return all
  end
```
Would that be an idea? I mean mapping the second to the first.
(off course in this particular instance it would be` .values `, but i guess that would be a runtime and as such another discussion)

If you think it's an acceptable idea but don't want to do it yourself, i can have a shot. aka thanks for the invite :-)

**Comment by rubys** [comment]
In Ruby, collect is a synonym for map.  JavaScript has a map method.

collect could be added to the functions filter, but instead of expanding as you describe, it probably should make use of the map function.

**Comment by dancinglightning** [comment]
I'm just learning js, but the net says that map is only defined on Array. The example is doing the collect over a hash / object.
And i know that collect is map, but i still use collect when i want to collect (ie am mostly interested in the result) and map, when the result is irrelevant. I mean that there is a case to rewrite collect (and possibly inject) and leave map as is, so one can use js map when one wants.

**Comment by rubys** [comment]
`map` is indeed only defined on an array in js.

I'll admit that is seems weird to me to use `map` when the result is irrelevant.  That is what `each `is for.

Also, that doesn't read like correct Ruby to me.  `collect` when applied to a Hash will return both a key and a value.

**Comment by dancinglightning** [comment]
do you mean hash will pass key and value ?

How do you suggest to handle this then? It is 4 lines js vs 1 ruby

**Comment by rubys** [comment]
What I meant is that (with Ruby semantics), `x` would be an array in the following:

```
$ irb
irb(main):001:0> {a:1}.collect {|x| x}
=> [[:a, 1]]
```

If I were reading the code you originally posted, it wouldn't be obvious to me what it does.  As someone who knows Ruby, it doesn't do what I would expect.  And knowledge of JavaScript wouldn't add any insight.

On the other hand, I would understand the following:

```ruby
def labels
  @buckets.values()
end
```

This will work if you include the underscore [library](http://underscorejs.org/) and filter.  It is also something that should be supported by the functions filter if es2017 support is opted in.  (At the moment, es2015 support is under development, but work could begin on es2017).

Meanwhile, the following will work without any filters:

```ruby
def labels
  Object.values(@buckets)
end
```

**Comment by dancinglightning** [comment]
Ok, can live with that for now.
Shall we map the values, just like the keys already is?

**Comment by rubys** [comment]
Only if es2017 is opted in.  I believe that I have completed the harder change (async/await), though only as a filter.  I'm going to look into whether it is possible to move this from a filter to converter/send.rb.  Also, if es2017 is opted in, then filter/underscore should no longer map x.values() to _.values(x).

**Comment by rubydesign** [comment]
guess this is done
