### ISSUE TITLE
el for apps

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#15]
Apps **need** an element that they target.
I've been using options for now, as in
`options el: "#app"`

and that works off course. But since it's not an option, rather a necessity, i though it may be nice to make it is't own "method"

**Comment by rubys** [comment]
Agreed.  Care to make the change?  Please add a test case if you do.

**Comment by dancinglightning** [comment]
I'll give that a shot, seems "small enough" (so i don't choke)

**Comment by dancinglightning** [comment]
Done in  e60a451
