### ISSUE TITLE
upto -1 ?

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#16]
Like you wrote in the loop issue, upto creates a for loop. And i got that working and all works. But the index ...

As you wrote (for looping an array)
```ruby   
  0.upto(@products.length) do |i|
     code
   end
```
transforms to 
```javascript
   for (var i = 0; i <= this.products.length; i++) {
    code
    }
```

The `<=` makes it do that this loop runs off the end,  and so in every single use case i write 
`0.upto(@products.length -1)`

Should we include the `-1` in the transformation?

**Comment by rubys** [comment]
upto() should continue to match Ruby's semantics:

```
$ irb
irb(main):001:0> 0.upto(5).to_a
=> [0, 1, 2, 3, 4, 5]
```

Consider `for i in 0...products.length` instead.

**Comment by dancinglightning** [comment]
I haven't used a for loop in 15 years. Not really an option.

I understand the ruby conformance, but then in ruby i'd use `each`. I'll try around a bit, maybe i can use map for the loops.

**Comment by rubys** [comment]
`map` would be weird, as `map` explicitly collects up and returns the results.

`each` is perfectly acceptable.  `(0...length).each {|I| }` should indeed be mapped by the functions filters to `for (I=0; I<length; I++) {}`.  And when called with two dots, should produce `<=`.

**Comment by dancinglightning** [comment]
Sounds good. Though each is mapped to forEach now, so are you propsing to change that, or implement it on ranges only?

Not sure if you misunderstood though: i mean to use the js map function on array. Seeing as i iterate arrays.

**Comment by rubys** [comment]
on ranges only.  Other uses would continue to map to forEach.

**Comment by dancinglightning** [comment]
Ok, i'm understanding better. I promise to pick up that js book soon. 
But i think, this little knowledge i have does help to reveal isues that others could run into too.

So i am using `each` in most cases now and that works. Except a return from a block does not return from the function. "Off course" as it transforms into a method. I'll do a section on this iterating today and put that gotcha in there.

My current solution is to use the upto, as that transforms into for and the return works. 
Off course in ruby both those look like blocks and one really has to know the transformation, as opposed to know just ruby (the conformity argument). Is there a way around that ?

**Comment by rubys** [comment]
I know of no way around it.

`return` probably should have the following code:

```ruby
raise NotImplementedError, "return inside block" if @next_token == :return
```

**Comment by dancinglightning** [comment]
Yes, that's good.
Though that would require the auto-return for the blocks to be always on. As there has to be the return in the JS.
But i already thought that would be  a nice thing anyway: In blocks the last value being used is so ingrained in ruby that it is totally weird to have to write the return. The return also violates the "conformance" idea, as it means a different thing in ruby (ie return from the enclosing method)

Sadly, i feel this is a bit out of my reach still. I'll close this and start the next "thread"

**Comment by rubys** [comment]
I've implemented range.each: https://github.com/rubys/ruby2js/commit/0798d90d59670ff3600a3255e642455ed5508750

**Comment by rubys** [comment]
I've changed `.each`, `.each_value`, and `.each_key` to convert to `for` loops.  The first two only if es2015 support is enabled.

**Comment by dancinglightning** [comment]
certainly busy. I have an issue with if when i try this out, i'll open that
