### ISSUE TITLE
inject

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#17]
now i've rewritten all my loops and they mostly look good. There is the each over a hash with |key, value| , but i only have one, so that's ok.

But injects i have about 5 and thought that may be nice.  They go something like this at the moment:
```ruby
def total_shown(show)
      total = 0
      this.filteredCategories.each { |item| total += item[show] }
      return total
    end
```

and in ruby i would write 

```ruby
def total_shown(show)
      return  this.filteredCategories.inject(0) { |item , total | total += item[show] }
 end
```

What do you think?

**Comment by rubys** [comment]
I've mapped each_pair to Object.elements (es2017): https://github.com/rubys/ruby2js/commit/ebb10a6a9d0f40d22c6a2360a4c8ee61c49e4388

I've mapped inject to reduce (es2015): https://github.com/rubys/ruby2js/commit/ac4820fa8584b8892077964c7ecf09546ea5788f
