### ISSUE TITLE
es2015

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#19]
Still trying to get the es2015 code to work.
As a first impression i must say it is _very_ confusing. I think it would be best not to call es2015 a filter, it's more like a mode. It seems to change (not just add) so much basics that it should be much better documented, especially with Vue. Which leads to the issue:

In the console i can get a reduce working. Ie chrome seems es6 compatible, copied reduce code from the net works, and the inject converts correctly to reduce on static data.

But then the big fat arrow (my first contact). I was just about getting used to the this and that and using self got around that (no pun intended).
But with es2015 enabled, the vue filter seems completely broken. I can not access instance variables at all anymore and have tried everything i know.

I'm not sure if this may even be a vue thing? The this in vue methods may have been changed, i read that that is possible? 
Anyway, stuck with es2015 and vue.

**Comment by rubys** [comment]
This is indeed a bug; I've just pushed one part of a fix, and am working on the rest.  Shouldn't be much longer.

es2015 is an option -- check the README.  There is a filter which may be a convenient way to set the option as a default.

**Comment by rubys** [comment]
The above may not be complete.  Feel free to reopen if I missed anything.  Meanwhile, I'll continue testing my Vue apps against es2015.

**Comment by dancinglightning** [comment]
Ok, basic access restored, phew. Was thinking i was going ... for a while.
Also, had rather expected from the "use es2015 as default" comment that you are using it in your vue apps.
Still want to say about es, will open fresh one

**Comment by rubys** [comment]
I'm not yet using es2015, but hope to be doing so soon.  Here's a reasonably large app using Vue: https://github.com/apache/whimsy/tree/master/www/board/agenda/views

**Comment by dancinglightning** [comment]
gotta love the organisation :-)

**Comment by dancinglightning** [comment]
seems to work, but only with the latest pull. Which i thought was only whitespace.
Definitely magic going on
