### ISSUE TITLE
deriving from js namespaced classes

### ISSUE THREAD

**Issue by rubydesign** [rubys/ruby2js#23]
Js folks seem in the habit of scoping their stuff to an object that they then export. (my understanding)

In my particular case i have global object `xeogl` and i want to derive from a Model class, in js: `class Frame extends xeogl.Model`

In ruby i tried things like `class Frame < xeogl::Model` also with `.` , but whatever i put in from of the Model gets swallowed.

I can off course work around this by defining a global variable to refer to the class, which i will if #22 gets resolved. But i was wondering if ruby2js has something, or maybe should have ?
(I mean i can try if you push me in the right direction)

**Comment by rubys** [comment]
I'm not following.

Given the input:

```ruby
class Frame < xeogl::Model
end
```

The output without es2015 or greater is:

```javascript
function Frame() {
  xeogl.Model.call(this)
};

Frame.prototype = Object.create(xeogl.Model);
Frame.prototype.constructor = Frame
```

And with es2015:

```javascript
class Frame extends xeogl.Model {
}
```

Are you seeing something different, or what were you expecting?

**Comment by rubydesign** [comment]
Yes, can't blame you for not following that one, because it is the _wrong bug.
(Or no bug, i had found that out)

What i meant to say is calling new, eg `new xeogl.Model()` 
that's what i can't get to work

**Comment by rubys** [comment]
Try `xoegl::Model.new()`.  Meanwhile, please leave this issue open and I will look at supporting that syntax too.

**Comment by rubydesign** [comment]
Well, that's just me being silly. Though i catch it a fair bit, mixing the syntaxes. Both ways actually.

Will be all the happier when i'm back to safe bosom of ruby only. Thank you

**Comment by rubys** [comment]
Trust me, I added this support because _I_ mixed the syntaxes in this way often, and each time was confused when it didn't work until I figured it out.  As you can see, the fix was easy.
