### ISSUE TITLE
Ability to support <=> used for sorting

### ISSUE THREAD

**Issue by kevjett** [rubys/ruby2js#26]
I would like to have the ability to support <=> which is typically used for sorting.

Ex: 
`myarray.sort!{|a,b| a.age <=> b.age }` 

Converted to: 
`myarray.sort((a, b) => {if (a.age < b.age) {return -1} else {return (a.age > b.age ? 1 : 0)}})`

**Comment by rubys** [comment]
I was able to get the code to emit a more compact version:

```javascript
myarray.sort((a, b) => a.age < b.age ? -1 : a.age > b.age ? 1 : 0)
```
If es2015 is not opted into, the code that is produced is as follows:

```javascript
myarray.sort(function(a, b) {a.age < b.age ? -1 : a.age > b.age ? 1 : 0})
```

**Comment by rubys** [comment]
Fixed non-es2015 to add a return, thus:

```javascript
myarray.sort(function(a, b) {return a.age < b.age ? -1 : a.age > b.age ? 1 : 0})
```
