### ISSUE TITLE
Support methods called with no parameters

### ISSUE THREAD

**Issue by kevjett** [rubys/ruby2js#30]
Is there a way to support methods called in other places of the conversion that don't have any parameters?

```
def age_to_use
    25
end

def age_val
    case age_to_use
        when 1...50
            1
        else
            2
    end
end
```

Can it determine that age_to_use is a method in the current conversion and call it with parenthesis so it will call the function in JS? `age_to_use()`

**Comment by rubys** [comment]
Within the same class?  Yes.  I've done similar things for Vue.

Are you needing this for methods defined by superclasses?   That might be doable, but would require more work.

**Comment by rubys** [comment]
It looks like the problem is deeper: more specifically module support is not complete.  To see what I am saying, try changing `module` to `class` in that example and see what is produced.  'm' and 'f' will be defined as property getters, and the call to `m` will be changed to `this.m`, which is more in line with what you want.

Can I ask what you are using modules for?  Will you be needing `include` support?

**Comment by rubydesign** [comment]
Just some 2 Cent. 

Having worked with vue, where some of this is implemented, I think it's a weird thing to have to remember, I mean when it works. And obviously the conversion can never work as Ruby really does. 

Even moving a method in a class currently changes the way you have to call. Even if that's fixed, calling in different classes will need brackets, while in the class not. 

I have stopped using the feature in the Ruby way. 
Instead I use it to distinguish between methods and attributes. 


⁣Sent from TypeApp ​

**Comment by kevjett** [comment]
The conversion as a class produces this:

```
function M() {}; 
M.prototype = {
  get m() {
    return 25 * 2
  }, 
  get f() {
    return this.m
  }
}
```
But there is still a problem with `this.m` because javascript will return the "function" not the output of the function. Whether it's a class or a module it needs to "execute" the m function. Just like if the m function did have one argument.

Here it is with 1 argument:

`class M; def m(a); 25 * a; end; def f; m 2; end; end`

produces:

```
function M() {}; 
M.prototype = {
  m: function(a) {
    return 25 * a
  }, 
  get f() {
    return this.m(2)
  }
}
```

See that the m function is executed with that parameter? `this.m(2)`

So if it doesn't have a parameter for m then it should be `this.m()`

**Comment by rubys** [comment]
> But there is still a problem with this.m because javascript will return the "function" not the output of the function.

Nope.  That's not how getters work in JavaScript.  Try running the following:

```javascript
function M() {};
M.prototype = {
  get m() {
    return 25 * 2
  }, 
  get f() {
    return this.m
  }
};

var x = new M();
console.log(x.f);
```

The output will be `50`.  `x.f` will invoke the second getter.  And `this.m` will invoke the first getter.

Meanwhile, I still need to know how you intent to use your modules before I can make the right fix.

**Comment by kevjett** [comment]
Sorry, I totally missed that it used a getter instead of a function. You are completely right. So for your question on how it's used...I was not part of the original architecture of our RoR platform so I can't give a detailed answer but our modules are hundreds of single purpose formulas so I guess they used modules to think of these as "libraries of formulas" to use in other places. But the conversion of no parameter methods cause a problem because almost all of them call another method(formula) in the module. Some have parameters, some don't. Just want to see if the conversion can be somewhat smart enough to call the "no-paramter" methods with empty parentheses since there are hundreds. Does that help?

**Comment by rubys** [comment]
The "no-parameter" part I get.  It is the "libraries of formulas" part I don't get.

Let me try a different way.  I've modified and extended your test:

```ruby
module M
  def self.m
    25 * 2
  end 
          
  def self.f
    m     
  end    
end     

p M.f        
```

The modifications were the additions of `self`.

Can you modify this example to produce running Ruby code that mimics how you are using your module?

**Comment by rubys** [comment]
```ruby
module M; def m; 25 * 2; end; def f; m; end; end
```

now converts to:

```javascript
var M = {get m() {return 25 * 2}, get f() {return this.m}}
```

`include` support has also been added.
