### ISSUE TITLE
Needing help converting

### ISSUE THREAD

**Issue by Twisterking** [rubys/ruby2js#33]
Please help out a ruby noob here ... 😄 
I am trying to convert the following little repo to JS: https://github.com/datanoise/ruby-as2
I installed ruby2js (I think) properly and got it to run the local webserver like so: (prior to that I installed the needed gems with bundler)
```sh
bundle exec ruby ruby2js.rb --port=8080
```
This works properly, but after copy pasting the ruby code from https://github.com/datanoise/ruby-as2/blob/master/lib/as2/server.rb I immediately run into an error:
```sh
_WARN #<Ruby2JS::Error: class class at :6:2>
```
I don't need working JS code right away, just something to start of with. I am pretty good at JS but very sluggish with ruby.

I hope someone finds a couple of minutes to help! Thanks a bunch!

**Comment by rubys** [comment]
Quick note before heading out the door.  Line 6, change 'class MimeGenerator' to 'module MimeGenerator'.  Line 125, change "rescue" to "rescue => e".  Nested classes and catch statements without a variable aren't something I know how to implement in JavaScript.

**Comment by Twisterking** [comment]
Thanks a bunch @rubys!
This helped - I could now convert the interesting files and can start actually writing working JS code! 😄
