### ISSUE TITLE
code generated by `include` not working

### ISSUE THREAD

**Issue by djshitcoin** [rubys/ruby2js#36]
```ruby
class Entity
  include Stats
end
```
generates
```js
function Entity() {};

(function() {
  for (var $_ in Stats) {
    Entity.prototype()[$_] = Stats[$_]
  }
})()
```
which results in `Uncaught TypeError: Entity.prototype is not a function`. I think the parentheses after `prototype` are wrong.

**Comment by rubys** [comment]
I've pushed a fix.  FYI, if you enable `es2015` or higher, you will see the following instead:

```javascript
class Entity {};
Object.assign(Entity.prototype, Stats)
```
