### ISSUE TITLE
'Try' demo in README links to 404 page

### ISSUE THREAD

**Issue by knod** [rubys/ruby2js#38]
Would love to see this in action live!

**Comment by rubydesign** [comment]
Here is some vue code in ruby with a video of what it does

https://medium.com/rubydesign/a-vue-data-table-for-rails-6b692b21e83e

**Comment by knod** [comment]
@rubydesign : Thanks! I was hoping to see a live demo of this converter too.

**Comment by knod** [comment]
Is there no chance of a live demo?

**Comment by rubydesign** [comment]
Since Sam fixed the link and you can now convert "live", i don't understand what you mean.
Do you want to see the converted code run in the browser ?

**Comment by knod** [comment]
Oh, shoot, my mistake. Didn't read closely enough, so I thought they just closed it. Didn't see the commit in there. That looks great, thanks!
