### ISSUE TITLE
Deploy scripts compiled into JS

### ISSUE THREAD

**Issue by kirs** [rubys/ruby2js#4]
This is not an issue, more like a discussion.
Thank you @rubys for your work!

As a Capistrano maintainer, I'm looking into ways how to speedup the deploy.
You may heard about Capistrano alternative called [Mina](http://nadarei.co/mina/). It makes the deploy really fast by compiling the tasks listed in `deploy.rb` list into a bash script and then executing this single script on the server.

We can't compile Capistrano tasks into a bash script, because it's way too complicated and it depends on many factors. Obviously, Bash is not the language your Ruby DSL can be translated.
Our main bottleneck in Capistrano is making new SSH connections and executing single script on the server side with only one SSH connection could make it dramatically faster.

What do you think about the idea of translating Capistrano DSL into JS and executing it with Node?
Is it worth in your opinion?

**Comment by rubys** [comment]
I'm interested.  I'll take code patches with specs; alternately if you just want to create specs, I can write the code (most likely a capfile filter) that makes the spec pass.

I can definitely see how a single script would speed things up.  Perhaps mapping into Node would mean that Windows servers could be directly supported?

**Comment by kirs** [comment]
> Perhaps mapping into Node would mean that Windows servers could be directly supported?

Probably yes, but I don't think there are many users who wish to deploy Rails or other Ruby apps on Windows using Capistrano.

And of course, we will have to require installed Node on the server.

**Comment by rubys** [comment]
Discussion seems to have lapsed.  Closing for now.  Feel free to reopen if there is interest.
