### ISSUE TITLE
Single quotation marks are always turned into double quotation marks 

### ISSUE THREAD

**Issue by onnimonni** [rubys/ruby2js#40]
This ruby code
```ruby
def hello
  'hello world!'
end
```
converts into:
```js
function hello() {
  return "hello world!"
}
```
I was expecting it to be:
```js
function hello() {
  return 'hello world!'
}
```

**Comment by rubys** [comment]
Why is this important?  Both are equivalent from a JavaScript point of view.  I'd like to understand the underlying requirements more fully before proceeding.

**Comment by onnimonni** [comment]
It's not that important. There are some corner cases where strings get escaped incorrectly when they are used as parameters to shell commands. In those rare cases it's useful to be able to use both kind of quotes ' & " to circumvent the escaping problem.

**Comment by rubys** [comment]
The current code uses `.inspect` to escape propertly: https://github.com/rubys/ruby2js/blob/master/lib/ruby2js/converter/literal.rb

If there are corner cases that need to be handled, please open bug reports on those.  I also would not be opposed to adding smarter logic to see if there are embedded double quotes and be a little smarter about using single quotes when the result is shorter.

ruby2js uses an AST parser which converts both types of strings into the same type of node (:str).  It is indeed possible with a bit more work to find the original source and make decisions based on what is found there.  I'm not certain it is worth it.

**Comment by onnimonni** [comment]
I'm totally agree with you on this. I asked this because I originally thought it's simple to fix.

**Comment by jaredcwhite** [comment]
Grooming the backlog…looks like we can close this.
