### ISSUE TITLE
Use .includes instead of .indexOf if eslevel is bigger than 2016

### ISSUE THREAD

**Issue by onnimonni** [rubys/ruby2js#44]
We could use `.includes` instead of `.indexOf` if user asked eslevel: 2016 or later.
This would produce more cleaner code.

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by rubys** [comment]
This and #45 are great ideas!  Let me know how you would like to proceed.  I invited you as a collaborator, and as long as you update the README, specs, and code at the same time, feel free to push your changes directly.  Alternately, let me know, and I will make these changes.

**Comment by onnimonni** [comment]
Thanks! I'll propably ask for a code review first few times so that we are on the same page 👍
