### ISSUE TITLE
Support irange.to_a

### ISSUE THREAD

**Issue by onnimonni** [rubys/ruby2js#45]
I'm just putting this here as a memo to myself. I will create a PR a bit later 👍 

We could quite easily support following notation:
```ruby
(0..4).to_a
```

In javascript:
```js
[...Array(5)].map((_,i) => i);  // [0, 1, 2, 3, 4]
// Or
[...Array(5).keys()] // [0, 1, 2, 3, 4]
```

I know that full irange support is quite hard but I know that we already do support it in few contexts.

Source: https://stackoverflow.com/questions/3746725/create-a-javascript-array-containing-1-n

**Comment by onnimonni** [comment]
@rubys do you have any example where you have checked the followng ast nodes?
I have the problem that if I just add:
```ruby
module Ruby2JS
  class Converter

    # (irange
    #   (int 1)
    #   (int 2))
    handle :irange do |*args|
      # My code here
    end
  end
end
```

I can't yet tell if the line will follow up with `.to_a`?.

For example `to_js('(1..5).to_a')` will only get [1,5] into the `args`.

I don't know how to fully support `irange` but I would like to start from this specific point.

**Comment by onnimonni** [comment]
I guess I need to trick the `:send` instead:
```ruby
Parser::CurrentRuby.parse("(1..5).to_a")
=> s(:send,
  s(:begin,
    s(:irange,
      s(:int, 1),
      s(:int, 5))), :to_a)
```

**Comment by rubys** [comment]
Look at how `converter/block.rb` handles `:step`
