### ISSUE TITLE
Simple Class Example Questions

### ISSUE THREAD

**Issue by jakehow** [rubys/ruby2js#49]
Hi.  I just started playing around with this gem and had some questions about how things should work.  I am not sure if these items have been discussed elsewhere.

Here is a sample ruby program:

```ruby
class App
  def run
    test_method
  end

  def test_method
    puts 'test'
  end
end

App.new.run()
```

With output:
```shell
➜ ruby app.rb 
test
```

If I load this program into ruby2js using the following setup:

```ruby
require 'ruby2js/filter/functions'

ruby = File.read('./app.rb')

puts Ruby2JS.convert(ruby, eslevel: 2017)
```

I get the following output:

```
class App {
  get run() {
    return test_method
  };

  get test_method() {
    return console.log("test")
  }
};

new App.run()
```

There are 3 issues that I see here:

1. the call to run cannot be chained like this.  If I wrap `App.new` in parenthesis manually, it produces working code: `(new App).run()`

2. I have not added the return filter, so adding the return statements when calling a method as the last line in a method body is confusing to me.

3. Calling test_method without arguments in ruby does not produce valid code in javascript.  I see there was already some discussion of this in #30 regarding modules, but classes don't seem to be generating valid code for this case either.

Expected output from my program should be something like:

```javascript
class App {
  get run() {
    return this.test_method
  };

  get test_method() {
    return console.log("test")
  }
};

(new App).run
```

I can get the program to compile to this definition by calling self explicitly in the definition of `#run` in the ruby file and wrapping `App.new` in parens.  Should the manual inclusion of self be required for this code?

Thanks for the cool project!

**Comment by rubys** [comment]
Point #1 is definitely a bug.

As for #2: A getter without a return statement does not make sense, so a return is added even without the return filter.  Obviously, an underdocumented feature.

As for #3: ruby2js uses the presence or absence of parenthesis to distinguish between property accesses and method calls.  Your last line contains parenthesis, so this is interpreted as calling a method.  Either (a) add parenthesis to the method definition, thus: `def run()`, or (b) drop parenthesis on the method call.

**Comment by rubys** [comment]
#1 is still a bug, but I'll note that if you added parenthesis there too, it would work:

```ruby
class App
  def run()
    test_method
  end

  def test_method()
    puts 'test'
  end
end

App().new.run()
```

**Comment by jakehow** [comment]
This works:

```ruby
class App
  def run()
    self.test_method()
  end

  def test_method()
    puts 'test'
  end
end

(App.new).run()
```

Is requiring the parens on methods an intentional feature to enable using getters on JS classes?

**Comment by rubys** [comment]
> Is requiring the parens on methods an intentional feature to enable using getters on JS classes?

Short answer: yes.  Without any other knowledge (which would be provided by filters), both of the following would be treated the same:

```javascript
name.length
name.toString
```

The former would extract the length property.  The latter would extract a bound function call, but not actually make the call.  In Ruby, both would be method calls.

I've pushed a fix for `new App.run()`: https://github.com/rubys/ruby2js/commit/87b67ed75d9372bfdc713fa3153bac9f851b44b0.

**Comment by jakehow** [comment]
@ruby Is the current need for the explicit call to self a bug or something that should be handled by a filter?

Other than that we can probably close this.

**Comment by rubys** [comment]
I'm going to look into that shortly.  I expect it will be a matter of a few lines and a test case.
