### ISSUE TITLE
functions filter: keys, values and entries don't seem to work

### ISSUE THREAD

**Issue by sebbASF** [rubys/ruby2js#50]
Tried the following:
$ echo "h.inspect;h.keys;h.values;h.entries;" | ruby demo/ruby2js.rb -f functions
JSON.stringify(h);
h.keys;
h.values;
h.entries

So inspect is translated, but keys etc are not
Yet the listing of functions translations implies that they should be converted.

**Comment by sebbASF** [comment]
I've since found out that the syntax is h.keys(), however this is not documented as such:
$ echo "h.inspect;h.keys();" | ruby demo/ruby2js.rb -f functions
JSON.stringify(h);
Object.keys(h)

So this is really a documentation bug

Also it looks like .values and .entries are not supported; my bad.

**Comment by rubys** [comment]
I'll first describe what does work, then we can work backwards from there as to what should work.

$ echo "h.inspect;h.keys();h.values();h.entries();" | ruby demo/ruby2js.rb -f functions --es2017
JSON.stringify(h);
Object.keys(h);
Object.values(h);
Object.entries(h)

Two things are going on here.

1) Some of these conversions require ES2017 support to be enabled, which pretty much rules out Internet Explorer: https://caniuse.com/#feat=object-entries.

2) Properties and methods are handled differently between JavaScript and Ruby, so at times ruby2js requires parenthesis to be used to disambiguate.  Deciding when they should be required and when they are not is a judgement call, and I may not have gotten all these decisions right.  And I certainly haven't documented it well enough.
