### ISSUE TITLE
Feature request: Method Inheritance

### ISSUE THREAD

**Issue by buhrmi** [rubys/ruby2js#55]
Hi all,

the following code will correctly compile and output `2` on the javascript console:

```ruby
class Foo
  def val
    2
  end

  def initialize
    puts val
  end
end

Foo.new
```
however, the following code will output `undefined` in javascript, but still outputs `2` in ruby.

```ruby
class Foo
  def val
    2
  end

  def initialize
    puts val
  end
end

class Bar < Foo; end

Bar.new
```

**Comment by rubys** [comment]
It looks like this will work as you expect it if you add a `require 'ruby2js/es2015'` (or later).  The bug here is that the code that emits class support for ECMAScript prior to ES2015 doesn't add an implicit constructor that calls `super`.

**Comment by buhrmi** [comment]
That works, thank you 😄

**Comment by rubys** [comment]
That was a workaround.  It was a real bug.
