### ISSUE TITLE
Lambda functions added to hash don't use ES6 arrow functions

### ISSUE THREAD

**Issue by jaredcwhite** [rubys/ruby2js#57]
When I'm defining a hash that includes lambda procs as values for the keys, I seem to get an odd shortening of the output JS syntax that technically works when executed, but it seems to be the old `function` scope behavior rather than an arrow function which inherits the parent `this`. For example, if I convert this Ruby code:

```ruby
class Test
  def initialize
    this.data = "abc"
    hash = {
      callback: ->(x) {
        console.log(this.data);
        return x
      }
    }
    hash.callback(123)
  end
end
```

I get this:

```js
class Test {
  constructor() {
    this.data = "abc";
    let hash = {callback(x) {console.log(this.data); return x}};
    return hash.callback(123)
  }
}
```

And `this.data` is `undefined` in the callback function.

I expect instead to see this:

```js
class Test2 {
  constructor() {
    this.data = "abc";
    let hash = {callback: (x) => {console.log(this.data); return x}};
    return hash.callback(123)
  }
}
```

However, if I modify the Ruby code to assign the callback separately:

```ruby
    hash = {
    }
    hash[:callback] = ->(x) {
      console.log(this.data);
      return x
    }
```

Then I get the expected JS with the arrow function:

```js
class Test {
  constructor() {
    this.data = "abc";
    let hash = {};

    hash.callback = (x) => {
      console.log(this.data);
      return x
    };

    return hash.callback(123)
  }
}
```

Alternatively, if I add parentheses around the lambda within the hash, that also outputs the correct syntax.

```ruby
class Test
  def initialize
    this.data = "abc"
    hash = {
      callback: (->(x) {
        console.log(this.data);
        return x
      })
    }
    hash.callback(123)
  end
end
```

**Comment by jaredcwhite** [comment]
@rubys Wow, that was quick! 😄 Just one thing though… I think I goofed and forgot that it would be more idiomatic to use `self.` rather than `this.` in the Ruby code…should that also be taken into account?

**Comment by rubys** [comment]
Version 3.3.5 will also handle the following:

```ruby
class Test
  def data
    "abc"
  end

  def initialize
    hash = {
      callback: ->(x) {
        console.log(data);
        return x
      }
    }
    hash.callback(123)
  end
end
```
