### ISSUE TITLE
Method Inheritance cont'd

### ISSUE THREAD

**Issue by buhrmi** [rubys/ruby2js#59]
When compiling this code

```ruby
class Foo
  def val
    2
  end
end

class Bar < Foo
  def initialize
    puts val
  end
end

Bar.new
```

the generated code throws the exception `val is undefined`. I think this is because the generated code references `val` even though it should be `this.val`.

Same thing happens in this case:

```ruby
module Foo
  def val
    2
  end
end

class Bar
  include Foo
  def initialize
    puts val
  end
end

Bar.new
```

**Comment by jaredcwhite** [comment]
@buhrmi I think you have to put `super` at the top of the `initialize` method in order for the variable to accessible (I get a JSS error otherwise). I've also found I need to add `self.` before the variable, as that's the only way to ensure that it will convert to `this` in the output JS.

**Comment by jaredcwhite** [comment]
Ah, I see what you're saying about the method inheritance…ideally you wouldn't need to use self. (But the point about super is still worthwhile…)

**Comment by buhrmi** [comment]
@jaredcwhite thanks for the hint to add ´self.´. it works. But if the ´intialize´ method is inside the main class, ruby2js is smart enough to add the ´this´ itself. so I thought it should be smart enough to add the ´this´ in subclasses/module users too

**Comment by rubys** [comment]
ruby2js could only be smart enough if both classes were in the same source file

**Comment by jaredcwhite** [comment]
Grooming the backlog…looks like we can close this.
