### ISSUE TITLE
rails 5.1  undefined method `empty?' for Ruby2JS::Converter

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#6]
Hi,
I am learning Vue and after 15 years of ruby am having trouble with all those braces and semicolons.
I've been using opal up to now, but to write vue code, it is overkill and introduces an unnecessary layer, so i was very happy to find this approach.

I am on 5.1 and to even get that up, i had to clone and put the gemspec in a file, so i could change the Rails::Template line 20 from *
Mime::JS 
to
Mime[:js]

But then i get the title error, somewhere deep in rack, and so i presume this is due to a rails change.
I read that you also use this with vue (and react) so i was wondering what rails version, and what the timescale for upgrading is?

As a side, is it possible to use ruby2js in the asset pipeline too ?

Thanks
Torsten

*
(I can push that change if you want)

**Comment by rubys** [comment]
A pull request would be appreciated; a test case would be appreciated even more.  :-)

All development and testing of Vue with Ruby2js has been with Sinatra and Wunderbar; with the largest example being: https://github.com/apache/whimsy/tree/master/www/board/agenda

That being said, getting Rails up and running given test cases should be straightforward, and I will gladly accept pull requests and/or test cases.

**Comment by dancinglightning** [comment]
Ok, pull requests coming, i have a little time, not much though.

I generally make an issue for each pull request, and the first will have to be the gemspec thing, just so i can get working.

Then i'll try to get it working for rails, might have to dig a bit for that.

But you can tell me already how you would want tests done for that. I didn't find sinatra tests to get an idea. Especially since neither sinatra or rails are in the gemfile.

**Comment by dancinglightning** [comment]
Ok, i patched an empty in there, but the next thing i get is a missing `bytesize` method, also on the converter.

So the way i am reading this code, the conversion is returning a Converter instance , in rails as in sinatra.
But whatever is receiving it, seems to want a String or something. So what is the ruby2js way of getting the final string output ?

**Comment by dancinglightning** [comment]
Nice, so that's done in 6435406c67b2f92e48f2d54fed5909391964a3e4
On to haml
