### ISSUE TITLE
Request for new functions: tap and yield_self/then

### ISSUE THREAD

**Issue by jaredcwhite** [rubys/ruby2js#65]
I might take a stab at these soon…not sure if there's a good way to do `then` as that's a pretty common part of Promise-style chaining, but it's just an alias for yield_self so that seems doable at least.

**Comment by rubys** [comment]
Can I get you to sketch out the mappings you would like to see supported?

Example.  Input Ruby:

```ruby
5.yield_self {|n| n*n}
```

output JavaScript:

```javascript
(n => n * n)(5)
```

`tap` would differ in that it would have a trailing `return n` appended.

Anything I'm missing?

Note: a future version of JavaScript may map one or both of these to the [pipeline operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Pipeline_operator).

**Comment by jaredcwhite** [comment]
@rubys Nice! You beat me to it 😊
