### ISSUE TITLE
Adding async prefix for blocks

### ISSUE THREAD

**Issue by jaredcwhite** [rubys/ruby2js#69]
I noticed a pattern in a recent JS example like this:

```js
it("runs some code", async () => {
   // …
})
```

I'm trying to figure out a good way to express that here…something like this feels obvious but probably not ideal from a syntax parsing perspective:

```ruby
it "runs some code" async do
  # …
end
```

I suppose a new keyword could be introduced (`asyncdo`?)…not thrilled with that idea either.

**Comment by rubys** [comment]
The following will produce the intended result, but isn't elegant:

```ruby
it "runs some code", async(proc do
   # ...
end)
```

The following is closer to being elegant (note, however, the extra comma required before the keyword `async`), and can be handled by `converter/block.rb` by transforming the AST of the latter example into the AST of the former and then processing the result.

```ruby
it "runs some code", async do |x|
 
end
```

**Comment by jaredcwhite** [comment]
👆that looks like a good solution…bridges the gap nicely.
