### ISSUE TITLE
No gemspec

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#7]
There is no gemspec in the root folder, so one can not use the git version from bundler.

This makes trying it out unnecessarily difficult.

As a side: bundler includes rake tasks to build and publish gems, so there is no need to have your own. You just add this to your Rakefile:
```
require "bundler"
Bundler::GemHelper.install_tasks
```

and then can do 
`rake build` to build a package, or 
`rake release` to upload it to rubygems

**Comment by rubys** [comment]
Note: what is currently being used is the package task that is included in Ruby itself:

https://ruby-doc.org/stdlib-2.3.3/libdoc/rubygems/rdoc/Gem/PackageTask.html
