### ISSUE TITLE
Logo Idea

### ISSUE THREAD

**Issue by jaredcwhite** [rubys/ruby2js#70]
I was thinking it'd be neat to have a logo for the project, something that could tie in both Ruby and JS branding concepts, and I came up with this:

<img src="https://user-images.githubusercontent.com/658496/97787372-e529b380-1b6e-11eb-9261-7dab5686d534.png" width="200" />

I like how the Ruby is outlined so it looks a bit like a blueprint, and it's "casting a shadow" over the JS. The JS itself is exactly the font of the [JS logo](https://github.com/voodootikigod/logo.js/blob/master/js.svg) and the yellow color is also pulled from there.

Let me know if you have any suggestions!

**Comment by jaredcwhite** [comment]
Here's an alternative version with the Ruby outline brighter, almost white:

<img src="https://user-images.githubusercontent.com/658496/97787437-6719dc80-1b6f-11eb-86e9-35c54c3825aa.png" width="200" />

**Comment by rubys** [comment]
What I used previously: http://intertwingly.net/svg/ruby2js.svg; as you can see, for example, here: http://intertwingly.net/blog/2015/04/01/Ruby2JS-2-0

I'm not wedded to it, but I do have a preference for logos with a clear background; and for there to be a SVG version of the logo.

**Comment by jaredcwhite** [comment]
Oh yeah, I was doing this all in Affinity Designer so SVG's no issue.

I'll try to find a way to do something that's more of a symbol, rather than a solid square…

**Comment by jaredcwhite** [comment]
Here's another take on the logo that gets rid of a solid background and turns it into more of a symbol. I also made it sure it exports well as an SVG. I'd probably recommend a bit of a drop shadow when it's on top of the light background…on a dark background, it really pops as-is.

<img src="https://user-images.githubusercontent.com/658496/100415545-425f3a80-3031-11eb-890e-bfd2d533ade0.png" width="139">

**Comment by rubys** [comment]
Looks nice.  WFM.

**Comment by jaredcwhite** [comment]
Cool, I'll add the files into the repo somewhere shortly, and plan on using them for the documentation website. I still kinda like the second version of the original square as well, so I'll include both that and the new symbol/logo.
