### ISSUE TITLE
Additional niceties from Ruby corelib/stdlib and even ActiveSupport-isms?

### ISSUE THREAD

**Issue by jaredcwhite** [rubys/ruby2js#71]
I'm thinking of starting a list of some obvious niceties we could look at implementing from Ruby's corelib/stdlib, and maybe even popular libraries like ActiveSupport (.present? would be awesome, for example…I always hate how verbose simple string checking has to be in JS). I also think it's likely some will make sense as function filters directly and others might be better suited to implementing via additional NPM packages and imported in.

Maybe using the wiki here for a page to start with would make sense…~~or keep a running list in this issue.…~~
https://github.com/rubys/ruby2js/wiki/Ruby-methods-possibly-supported-in-the-future

**Comment by rubys** [comment]
Just thinking out loud here... .assuming one or more of these results in a non-trivial expansion, it might make sense to create npm modules (perhaps under the `@ruby2js` scope/namespace?).  A filter might not be needed, but perhaps it could do whatever transformation is needed (if any) and insert the necessary `import` statements.

**Comment by jaredcwhite** [comment]
Definitely like the `@ruby2js` namespace idea, and an automatic import sounds interesting as well!

**Comment by rubys** [comment]
An example of automatic imports, try going to https://whimsy.apache.org/ruby2js/node/esm and entering the following

```ruby
system "echo hi"
```

The resulting javascript will be:

```
import child_process from "child_process";
child_process.execSync("echo hi", {stdio: "inherit"})
```

**Comment by jaredcwhite** [comment]
Very cool!

**Comment by rubys** [comment]
As luck would have it, npm already has a SecureRandom.alphanumeric implementation in [base62-random](https://github.com/deployable/base62-random).  I've committed experimental support for this (without docs) in https://github.com/rubys/ruby2js/commit/6e11f3122e57dc85edd89ed3c937357a0b95329c

Disjointed thoughts:

* the code to add CJS `require`s and ESM `import`s isn't very DRY.  That likely should be refactored by having all code generate `s(:import)` nodes, and having the converter for import do the right thing; `cjs` and ``esm` could be an option, and the `node` and `esm` filters could influence the default for this option, probably with the default ending up being esm UNLESS the node filter is used AND the esm filter is NOT used.
* While this an similar filters can be individually included, there may be value in having an umbrella `stdlib` filter that combines all of relevant filters.
* There may be value in tracking the imports that are found and having the object that `Ruby2js.convert` returns have a method that returns this list.  
* while `base64_random` is relatively unlikely to be collision with variable names in the converted script, it isn't impossible for it to be a collision.  Over time, as more modules are created, this chance goes up.  Perhaps a convention like adding a trailing `$` to such variable names might be worth exploring, as such would never be a valid Ruby identifier.

**Comment by jaredcwhite** [comment]
I like all of those ideas, and I would *love* to have a more official subsystem for imports, not only on the tracking output side as you mentioned, but I could also envision setting up some autoimports. Not necessarily something full-blown ala Zeitwerk, but maybe a situation where the converter is passed a hash of classes/methods -> paths and then when it encounters that class or method used in a file it makes sure that gets imported from elsewhere in the source tree. For example I write a lot of files where I always have to import three things from one particular file, and if that was just assumed dynamically it would clean things up very nicely. It's the kind of stuff that gives an even more Ruby-esque feel.

**Comment by rubys** [comment]
> but maybe a situation where the converter is passed a hash of classes/methods -> paths and then when it encounters that class or method used in a file it makes sure that gets imported from elsewhere in the source tree

Something like https://github.com/rubys/ruby2js/commit/dacda5bc06d20178446a21294b634aa33dd41654 perhaps?
