### ISSUE TITLE
Expand test coverage for sourcemap generation

### ISSUE THREAD

**Issue by jaredcwhite** [rubys/ruby2js#75]
@rubys I found a recent regression that was causing sourcemap output to fail due to a nil AST node location, so that's fixed now in the latest release and I added a simple test (sourcemap_spec.rb) to verify sourcemaps can be generated, but that should probably get built out a bit more. I don't know enough about the possible use cases to know what the ideal test coverage should be.

**Comment by rubys** [comment]
Good catch!

There is a lot to unpack here:

First, sourcemap generation isn't much code, and what code there is is a literal implementation of the spec.  Add to that the fact that the output is encoded in a way that makes it impossible to verify by visual inspection.  The net of this is that this isn't so much a matter of code path coverage as it is a matter of being able to handle all the types of data that can be thrown at it.

As to data, nodes can either have a source location or they don't.  Most of the time it doesn't matter, but as it was previously coded it did matter for the top node of the tree.  Your fix significantly increased the chance that the top node will have a source location, but there still are edge cases where it will not.  I went the other way and eliminated the need for the top location to have a source location, and even added a test case where there aren't any nodes.

The only other consideration that needs to be handled is one where there are multiple source files represented.

**Comment by jaredcwhite** [comment]
Yeah that all makes sense. As long as it's very unlikely for the sourcemap's output to be invalid (or worse, crash), that should be fine. Thanks for taking a closer look.
