### ISSUE TITLE
Something akin to method_missing support via Proxy?

### ISSUE THREAD

**Issue by jaredcwhite** [rubys/ruby2js#78]
I'm just starting to read up on the [Proxy API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)—and in fact feel a bit silly this hasn't been on my radar to date—and it's gotten me thinking if there could be some way of utilizing it under-the-hood to facilitate `method_missing` type behavior. I think the challenge is that a proxied object is a separate thing from a normal JS object/class definition…not a unified declaration like in Ruby, so it might be pretty tricky syntax-wise.

**Comment by rubys** [comment]
Sketch of a possible approach: when processing a class scan for a `method_missing` method.  If present, append a dollar sign to the class name, and emit an additional function with the original class name that returns a proxy. 

Example potential output to illustrate the idea:

```javascript
class Roman$ {
  to_roman(string) {
    const conversion = {m: 1000, d: 500, c: 100, l: 50, x: 10, v: 5, i:1};
    let values = string.split('').map(c => conversion[c]);
    for (let i=0; i<values.length-1; i++) {
      if (values[i] < values[i+1]) values[i] = -values[i];
    }
    return values.reduce((a, b) => a + b, 0);
  }

  method_missing(method) {
    return this.to_roman(method);
  }
}

function Roman() {
  return new Proxy(new Roman$(), {
    get(obj, prop) {
      if (prop in obj) {
        return obj[prop];
      } else {
        return (...args) => obj.method_missing(prop, args);
      }
    }
  })
}


let r = new Roman();

console.log(r.mcmlxi());
```

Note the `()` in the last line.  I can't figure out any way for the proxy `get` method to determine if the property being accessed is a going to be called as a function or is a getter.

**Comment by jaredcwhite** [comment]
That looks awesome! I suspect you have to add that `()` in because the return value from the proxy `get` is a function, not a value, so it's assuming it needs to be executed as a function. The alternative would be to run `method_missing` within `get` directly and return that return value. Unfortunately we have no way of knowing if a particular missing call should be done as a function call or a property getter. Probably best to stick with functions.

**Comment by rubys** [comment]
Non-standard, but if `method_missing` is defined to take only a single argument, it will be called directly without being wrapped in a function.  This allows more functionality, at a cost of being a slightly different semantics than Ruby's `method_missing`.
