### ISSUE TITLE
Feature request: Automatically add named exports

### ISSUE THREAD

**Issue by jaredcwhite** [rubys/ruby2js#84]
Previously requested by @buhrmi in https://github.com/whitefusionhq/rb2js-loader/issues/3

> Hello,
> 
> my main use case for rb2js is to share code between server and client. The issue I'm facing is that in order to use a class/module compiled through rb2js-loader, I have to explicitly `export` that class/module. That obviously prevents me from using that file server-side.
> 
> My idea is to add a configuration option to instruct rb2js-loader to automatically export classes/modules. For example, a file `bla.js.rb` with the contents
> 
> ```
> module Shared
>   def something
>   end
> end
> ```
> 
> would automatically export the module `Shared` and make it importable via `import { Shared } from 'bla.js.rb'`

**Comment by rubys** [comment]
I'm not sure I understand the use case:

 * For starters, recent releases of Node.js have pretty decent support for ESM
 * For older releases, one can use the [esm](https://www.npmjs.com/package/esm) module on npm
 * And, of course, there always is [@babel/register](https://babeljs.io/docs/en/babel-register/)
 * Finally, I did create a cjs filter ([tests](https://github.com/rubys/ruby2js/blob/master/spec/cjs_spec.rb#L18)) attempting to parallel the esm filter that would take the same input and produce cjs `module.exports` and `require` statements, which could be handy if the same source was processed twice with different filters, one for the client and one for the server.

All that being said, an autoexports feature is a good idea.  It probably should also export all constants, and only the ones defined at the top level (i.e., no nested classes).  And probably should also have a magic comment that disables it.

**Comment by buhrmi** [comment]
This is about being able to execute the same code server-side and client-side (after transpiling the code). Having keywords like `export` in a ruby file prevents that file from being executed on the server.

**Comment by rubys** [comment]
@burmi I'm sorry, but I still don't understand.

[whimsy board agenda](https://github.com/rubys/whimsy-board-agenda-nodejs/tree/master/src/server) is the server code of a project written in Node.js.  If you look at the files in the [operations](https://github.com/rubys/whimsy-board-agenda-nodejs/tree/master/src/server/operations) and [sources](https://github.com/rubys/whimsy-board-agenda-nodejs/tree/master/src/server/sources) subdirectories, you will see both `import` and `export` statements.  This is made possible by the use of `@babel/register` in [server.js](https://github.com/rubys/whimsy-board-agenda-nodejs/blob/497166150053fb766d6b90b6136237e800e5d5b8/src/server.js#L9)

Another option I did not mention above is that there is a `require` filter which will inline the target of require statements.  This allows you to structure your code into separate files but they will all be merged into a single file with no `import` or `export` statements whatsoever.

Finally, I'm not sure what you are looking for, but if you want import and export statements __only__ on the client side, then you can take the source and process it with different filters.

**Comment by jaredcwhite** [comment]
I think the request is for code that can run server-side as "actual Ruby" and also client-side via Ruby2JS + Webpack. "Isomorphic" in other words. Is that right @buhrmi?

**Comment by buhrmi** [comment]
@jaredcwhite yes that is exactly right

**Comment by rubys** [comment]
Makes sense.  Thanks both!

I took a stab at implementing this.  Let me know if there is more that needs to be done.
